name: pymeasure
channels:
  - conda-forge
dependencies:
  - cloudpickle=1.6.0
  - numpy >1, <=2.1.2
  - pandas=2.2.3
  - pint=0.24.4
  - pyqt=5.15.11
  - pyqtgraph=0.12.4
  - pyserial=3.4
  - pyvisa=1.14.1
  - pyzmq=26.2.0
  - qtpy=2.4.3
# Development dependencies below
  - pytest-qt=4.2.0
  - pytest-runner=5.2
  - pytest=7.2.0
  - pytest-cov=4.1.0
  - pyvisa-sim==0.6.0
  - flake8=6.0.0
  - setuptools_scm # don't pin, to get newest features
  - sphinx=7.4.7
  - sphinx_rtd_theme=3.0.0
#  pip is currently not needed, but the recommended tool when packages that are unavailable on conda are required
  # - pip  # don't pin, to gain newest conda compatibility fixes
  # - pip:
