version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
    environment: .github/pymeasure.yml

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

formats: all
