name: pymeasure
channels:
- conda-forge
- defaults
dependencies:
- numpy=1.11.0=py35_1
- pandas=0.18.1=np111py35_0
- pip=8.1.2=py35_0
- py=1.4.31=py35_0
- pyqt=5.6.0=py35_2
- pyqtgraph=0.10.0=py35_0
- pyserial=2.7=py35_0
- pytest=2.9.1=py35_0
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- setuptools>27.3.0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- wheel=0.29.0=py35_0
- pyvisa==1.8
- pytest-qt==2.4.0
