name: pymeasure
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15.2
  - pandas=0.22.0
  - pyqt=5.6.0
  - pyqtgraph=0.10.0
  - pyserial=3.4
  - pytest=3.2.2
  - pytest-qt=3.2.2
  - python=3.5.6
  - pyvisa=1.9.0
  - qt=5.6.2
