name: pymeasure
channels:
- conda-forge
- defaults
dependencies:
- numpy=1.11.1=py34_0
- pandas=0.18.1=np111py34_0
- pip=8.1.2=py34_0
- py=1.4.31=py34_0
- pyqt=4.11.4=py34_4
- pyqtgraph=0.9.10=py34_1
- pyserial=2.7=py34_0
- pytest=2.9.2=py34_0
- python=3.4.5=0
- python-dateutil=2.5.3=py34_0
- pytz=2016.6.1=py34_0
- setuptools>27.3.0
- sip=4.18=py34_0
- six=1.10.0=py34_0
- wheel=0.29.0=py34_0
- pip:
  - pyvisa==1.8
  - pytest-qt==2.4.0
