name: pymeasure
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.18.1
  - pandas=1.0.1
  - pyqt=5.12.3
  - pyqtgraph=0.10.0
  - pyserial=3.4
  - pytest=5.3.5
  - pytest-qt=3.3.0
  - python=3.8.1
  - pyvisa=1.10.1
  - qt=5.12.5
