name: pymeasure
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.2
  - pandas=1.1.3
  - pyqt=5.12.3
  - pyqtgraph=0.11.0
  - pyserial=3.4
  - pytest=6.1.1
  - pytest-qt=3.3.0
  - python=3.9
  - pyvisa=1.10.1
  - qt=5.12.9
