name: pymeasure
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.4
  - pandas=0.24.2
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - pyserial=3.4
  - pytest=5.0.1
  - pytest-qt=3.2.2
  - python=3.7.3
  - pyvisa=1.9.1
  - qt=5.9.7
